### ISSUE TITLE
Broken menu?

### ISSUE THREAD

**Issue by mani1232** [Elytrium/LimboHub#2]
![image](https://github.com/Elytrium/LimboHub/assets/70480001/7a8a4115-82a9-4654-8318-cf5985c7e6e4)

```
{
  "versionInfo": {
    "name": "Velocity",
    "vendor": "Velocity Contributors",
    "version": "3.2.0-SNAPSHOT (git-37fedf50-b260)"
  },
  "platform": {
    "operatingSystemType": "Linux",
    "operatingSystemVersion": "6.1.0-10-amd64",
    "operatingSystemArchitecture": "amd64",
    "javaVersion": "20.0.1",
    "javaVendor": "GraalVM Community",
    "listener": {
      "listenerType": "epoll",
      "compression": "libdeflate (Linux x86_64)",
      "encryption": "OpenSSL 3.0.x (Linux x86_64)"
    }
  },
  "config": {
    "bind": "0.0.0.0:25565",
    "motd": "WorldMandia Proxy",
    "showMaxPlayers": 1000,
    "onlineMode": false,
    "preventClientProxyConnections": false,
    "playerInfoForwardingMode": "MODERN",
    "announceForge": false,
    "onlineModeKickExistingPlayers": false,
    "pingPassthrough": "DISABLED",
    "advanced": {
      "compressionThreshold": 256,
      "compressionLevel": 9,
      "loginRatelimit": 3000,
      "connectionTimeout": 30000,
      "readTimeout": 60000,
      "proxyProtocol": true,
      "tcpFastOpen": true,
      "bungeePluginMessageChannel": true,
      "showPingRequests": false,
      "failoverOnUnexpectedServerDisconnect": true,
      "announceProxyCommands": true,
      "logCommandExecutions": false,
      "logPlayerConnections": true
    },
    "query": {
      "queryEnabled": false,
      "queryPort": 25577,
      "queryMap": "Velocity",
      "showPlugins": false
    },
    "enablePlayerAddressLogging": true,
    "forceKeyAuthentication": false,
    "servers": {
      "server1": {
        "currentPlayers": 0,
        "host": "172.18.0.1",
        "port": 30000
      }
    },
    "connectOrder": [
      "server1"
    ],
    "forcedHosts": {
      "play.worldmandia.cc": [
        "server1"
      ]
    }
  },
  "plugins": [
    {
      "id": "protocolize",
      "name": "Protocolize",
      "version": "v2",
      "authors": [
        "Exceptionflug"
      ]
    },
    {
      "id": "commandblocker",
      "name": "CommandBlocker",
      "version": "1.3.1",
      "authors": [
        "TauCubed"
      ],
      "description": "It regex. It tab. but most important, It blocc.",
      "url": "https://gitlab.com/TauCu/command-blocker",
      "dependencies": [
        "protocolize"
      ]
    },
    {
      "id": "fastmotd",
      "name": "FastMOTD",
      "version": "1.0.3",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "description": "MOTD plugin that uses FastPrepareAPI.",
      "url": "https://elytrium.net/"
    },
    {
      "id": "limboapi",
      "name": "LimboAPI",
      "version": "1.1.16",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "description": "Velocity plugin for making virtual servers.",
      "url": "https://elytrium.net/"
    },
    {
      "id": "limboauth",
      "name": "LimboAuth",
      "version": "1.1.13",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "url": "https://elytrium.net/",
      "dependencies": [
        "limboapi",
        "floodgate"
      ]
    },
    {
      "id": "limbofilter",
      "name": "LimboFilter",
      "version": "1.1.11",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "url": "https://elytrium.net/",
      "dependencies": [
        "limboapi"
      ]
    },
    {
      "id": "limbohub",
      "name": "LimboHub",
      "version": "1.0.1",
      "authors": [
        "JNNGL"
      ],
      "dependencies": [
        "limboapi"
      ]
    },
    {
      "id": "limboreconnect",
      "name": "LimboReconnect",
      "version": "1.1.1",
      "authors": [
        "SkyWatcher_2019",
        "hevav"
      ]
    },
    {
      "id": "luckperms",
      "name": "LuckPerms",
      "version": "5.4.98",
      "authors": [
        "Luck"
      ],
      "description": "A permissions plugin",
      "url": "https://luckperms.net"
    },
    {
      "id": "skinsrestorer",
      "name": "SkinsRestorer",
      "version": "15.0.0-SNAPSHOT",
      "authors": [
        "knat",
        "AlexProgrammerDE",
        "Blackfire62",
        "McLive"
      ],
      "description": "Ability to restore/change skins on servers! (Offline and Online Mode)",
      "url": "https://skinsrestorer.net",
      "dependencies": [
        "floodgate"
      ]
    },
    {
      "id": "velocity_tools",
      "name": "VelocityTools",
      "version": "1.1.9",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "url": "https://elytrium.net/"
    }
  ]
}
```

```yml
version: "1.0.1"
# Available serializers:
# LEGACY_AMPERSAND - "&c&lExample &c&9Text".
# LEGACY_SECTION - "§c§lExample §c§9Text".
# MINIMESSAGE - "<bold><red>Example</red> <blue>Text</blue></bold>". (https://webui.adventure.kyori.net/)
# GSON - "[{"text":"Example","bold":true,"color":"red"},{"text":" ","bold":true},{"text":"Text","bold":true,"color":"blue"}]". (https://minecraft.tools/en/json_text.php/)
# GSON_COLOR_DOWNSAMPLING - Same as GSON, but uses downsampling.
serializer: LEGACY_AMPERSAND

main:
  # World file type:
  #  SCHEMATIC (MCEdit .schematic, 1.12.2 and lower, not recommended)
  #  STRUCTURE (structure block .nbt, any Minecraft version is supported, but the latest one is recommended).
  #  WORLDEDIT_SCHEM (WorldEdit .schem, any Minecraft version is supported, but the latest one is recommended).
  world-file-type: WORLDEDIT_SCHEM
  world-file-path: "hub.schem"
  # World time in ticks (24000 ticks == 1 in-game day)
  world-ticks: 1000
  # World light level (from 0 to 15)
  world-light-level: 13
  # Should we override block light level (to light up the nether and the end)
  world-override-block-light-level: true
  # Available: ADVENTURE, CREATIVE, SURVIVAL, SPECTATOR
  game-mode: ADVENTURE
  # Available dimensions: OVERWORLD, NETHER, THE_END
  dimension: OVERWORLD
  hub-command:
    require-permission: false
    aliases:
      - "hub"
      - "lobby"
  # Message that will be sent when player joins the hub.
  welcome-message:
    - ""
  # Title that will be displayed when player joins the hub.
  welcome-title: ""
  welcome-subtitle: ""
  welcome-title-fade-in-millis: 100
  welcome-title-stay-millis: 2000
  welcome-title-fade-out-millis: 100
  # Player will teleported back to the spawn position if it falls below the `y-limit` when enabled.
  enable-y-limit: true
  y-limit: -10
  # Try increasing this value if NPC skins are not loading.
  skin-load-seconds: 3
  world-coords:
    x: 0
    y: 0
    z: 0
  player-coords:
    x: 3.5
    y: 1.0
    z: 3.5
    yaw: 90.0
    pitch: 0.0
  # Menu that will be opened when player joins the hub.
  # Set to blank value (default-menu: "") to disable.
  default-menu: ""
  # List of boss bars that will be set for the player in the specified order. Set to empty list (bossbars: []) to disable.
  bossbars:
    - # Hides boss bar
      hidden: true
      name: "BossBar 1"
      progress: 1.0
      color: PINK
      overlay: PROGRESS
      # Set -1 to mark this boss bar as the last one. (Next boss bar won't be displayed)
      stay-time-millis: 5000
  sidebar:
    enabled: false
    title: "This is a sidebar."
    lines:
      - "&7Configure me in config.yml."
  # Commands that will be available in the hub.
  commands:
    - command: "menu"
      aliases:
        - "servers"
      # Action to perform when the command is executed.
      action:
        # Available values: DO_NOTHING, CLOSE_MENU, SEND_MESSAGE, OPEN_MENU, CONNECT_TO_SERVER, KICK_PLAYER, TELEPORT_PLAYER
        type: OPEN_MENU
        # Depends on action type:
        # DO_NOTHING: Not used.
        # CLOSE_MENU: Not used.
        # SEND_MESSAGE: Message to send, lines should be separated with {NL}.
        # OPEN_MENU: Menu ID
        # CONNECT_TO_SERVER: Server name (as in velocity.toml).
        # KICK_PLAYER: Kick reason
        # TELEPORT_PLAYER: Coordinates in "x y z yaw pitch" format.
        data: "menu"
  menus:
    - # Menu ID that will be used in OPEN_MENU actions.
      menu-id: "menu"
      title: "&8Menu"
      # Items that will be used in `menu-contents`.
      items:
        - # Any character that will represent this item in `menu-contents`.
          id: "."
          # Modern item ID, e.g. "minecraft:stone".
          item: "minecraft:black_stained_glass_pane"
          fallback-items:
            - "minecraft:white_stained_glass_pane"
          count: 1
          # Only used on legacy versions (1.12.2 and lower).
          data: 15
          has-color: false
          # You can get color value at https://notwoods.github.io/minecraft-tools/armorcolor/.
          color: 0
          enchanted: false
          # Player skin in "uuid;value" or "value" format
          # You can get these values at https://mineskin.org/ or https://minecraft-heads.com/.
          skull-owner: ""
          custom-name: ""
          lore: []
        - # Any character that will represent this item in `menu-contents`.
          id: "2"
          # Modern item ID, e.g. "minecraft:stone".
          item: "minecraft:grass_block"
          fallback-items: []
          count: 1
          # Only used on legacy versions (1.12.2 and lower).
          data: 0
          has-color: false
          # You can get color value at https://notwoods.github.io/minecraft-tools/armorcolor/.
          color: 0
          enchanted: false
          # Player skin in "uuid;value" or "value" format
          # You can get these values at https://mineskin.org/ or https://minecraft-heads.com/.
          skull-owner: ""
          custom-name: "&fServer-1"
          lore:
            - "&f"
            - "&fJoin version: &61.16+"
            - "&fServer version: &61.20.1"
            - "&f"
      # Menu content. The size of the menu depends on the length and number of lines.
      # For example, 6 lines of 9 characters each represent a 9x6 menu.
      # Each character represents an item (see `item-id`); space is an empty slot.
      menu-contents:
        - "........."
        - "....2...."
        - "........."
      # The default action to be performed when player clicks on slot.
      # Available values: DO_NOTHING, CLOSE_MENU.
      default-action: DO_NOTHING
      actions:
        - # List of slots in one of the following formats: "slotNumber", "column,row".
          slots:
            - "13"
          # Action to perform when player clicks on specified slots.
          action:
            # Available values: DO_NOTHING, CLOSE_MENU, SEND_MESSAGE, OPEN_MENU, CONNECT_TO_SERVER, KICK_PLAYER, TELEPORT_PLAYER
            type: CONNECT_TO_SERVER
            # Depends on action type:
            # DO_NOTHING: Not used.
            # CLOSE_MENU: Not used.
            # SEND_MESSAGE: Message to send, lines should be separated with {NL}.
            # OPEN_MENU: Menu ID
            # CONNECT_TO_SERVER: Server name (as in velocity.toml).
            # KICK_PLAYER: Kick reason
            # TELEPORT_PLAYER: Coordinates in "x y z yaw pitch" format.
            data: "server1"
  npcs:
    - display-name: ""
      x: 1.5
      y: 1.0
      z: 3.5
      yaw: 270.0
      pitch: 0.0
      load-skin: true
      # You can get skin properties at https://mineskin.org/.
      skin-data:
        uuid: "da6737a3-120d-465a-aadd-a99f69acaec2"
        value: "ewogICJ0aW1lc3RhbXAiIDogMTY4ODMwMTg4NjQzNywKICAicHJvZmlsZUlkIiA6ICI0NmJhMWQxNWY0OTM0ZGQ2OTQzZTE3YTMxNmQ0MTk5YiIsCiAgInByb2ZpbGVOYW1lIiA6ICJKYWtvYl9PU0giLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWRlZWRkMzUyMjJkYTNmMmUwZjViM2M1ODI5MWIyMWNhNTA5MGU5NjA4MGI3OTRlZDYwYTVjNmJjZDZhZmE3IiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0="
        signature: "R47MLfXip3htZ0gzMGDDeSI75e1kKHXGZXzAGoG6BYR5/6Rh3hQji9H0YEem/4oNxmOSrG0pgg8ku/DmHcGVsNijEQrq81fOl2Kvsx9T+udQfKI5bue0181OSoUHL9gMfXGXHiTwqhbR9s/sMf7wxNS9nlT/uTRsiLEk6juR2H6REXYC9CjqXMy6nYQHSacXALes+X3lRt6o1U9q36RdbtEhiSOqq/x0YxPPtmfX9L311Ruw17h1L6MKPpBXIlnFARP+zBO+jSjHvRO2W27Y8O/S+1ZTIbDAnP66Qit44PPhZfyqx4kHsA3009ijRT6NiBIF4Ws0D2iXQEkDNpVDAWvAsGq3Kh6UTplQcHjDqt0/6ENESmVP14fXIKBQG11isHjknsN2BvNDmnivOMO9h26Fz7+Dx4n/hFkJvdIJSydMLwn9MitEYV8oydTfjZHk4yGw4XewjdkosvuW+Myq8y2eb1JxBynghnVdK7DyISZY1KKb5VKYWg8LO/3rtuK/wGdS1fimZ29omjyNXtlGnt2Vnm6C1CjUu+3/u6/8WlR565541u/RoOGuea8MVenHoCD28ZOC0GnDqm8BIMP65tdJzBWZpA9BtfqWQmtV1yV4F0tVPuc71R+D271Sd8qUb7nyW3lKYMn2eIcYEI5ykrYC1IfEoJ9/Uw6o5RqAHm0="
        # (255 - all skin parts)
        # Sum of the following numbers:
        # Cape - 1
        # Jacket - 2
        # Left Sleeve - 4
        # Right Sleeve -  8
        # Left Leg - 16
        # Right Leg - 32
        # Hat - 64
        displayed-skin-parts: 255
      # Action to be performed when player clicks on NPC.
      action:
        # Available values: DO_NOTHING, CLOSE_MENU, SEND_MESSAGE, OPEN_MENU, CONNECT_TO_SERVER, KICK_PLAYER, TELEPORT_PLAYER
        type: OPEN_MENU
        # Depends on action type:
        # DO_NOTHING: Not used.
        # CLOSE_MENU: Not used.
        # SEND_MESSAGE: Message to send, lines should be separated with {NL}.
        # OPEN_MENU: Menu ID
        # CONNECT_TO_SERVER: Server name (as in velocity.toml).
        # KICK_PLAYER: Kick reason
        # TELEPORT_PLAYER: Coordinates in "x y z yaw pitch" format.
        data: "menu"
  holograms:
    - x: 5.0
      y: 100.0
      z: 3.5
      lines:
        - "&f"
```
